[global]
# If set to true, also look for and load .env files on top of the .envrc files.
# If both .envrc and .env files exist, the .envrc will always be chosen first.
load_dotenv=true

# Specify how long to wait before warning the user that the command is taking
# too long to execute. Defaults to "5s".
# A duration string is a possibly signed sequence of decimal numbers, each with
# optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m".
# Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
# This feature is disabled if the duration is lower or equal to zero. Will be
# overwritten if the environment variable DIRENV_WARN_TIMEOUT is set to any of
# the above values.
warn_timeout="5m"