---
# Name of the session
session_name: default

# Load session relative to config location (project root).
start_directory: "${tmuxp_start_directory:=./}"

# Run a specific script before tmux start
# before_script: ./script.sh

# Shell command to run before tmux windows and pane start
# shell_command_before: command

windows:
  - window_name: " "
    focus: True
    layout: main-horizontal
    options:
      main-pane-height: 60
    panes:
      - focus: true
        shell_command:
          - vim +"CocCommand explorer"
      - null
      - null
  - window_name: " "
    panes:
      - focus: true
